---
    name: Role-Testing
    'on':
      pull_request:
      push:
        branches:
          - dev
    
    
    jobs:
    
      pangenotyping:
        name: Pangenotyping_role
        runs-on: ubuntu-latest
        
        steps:
          - name: Check out the codebase.
            uses: actions/checkout@v2
    
          - name: Set up Python 3.
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
    
          - name: Install test dependencies.
            run: pip3 install ansible-core
          
          - name: Install community.general collection
            run: ansible-galaxy collection install community.general
            
          - name: Install Pangenotyping role and run tests.
            run: ansible-playbook tests/test.yml
            